framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    session:
        cookie_lifetime: 172800
        gc_maxlifetime: 172800

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
